// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvjgwhnzpsddkksqjjky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2amd3aG56cHNkZGtrc3Fqamt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODU0NDQsImV4cCI6MjA1OTk2MTQ0NH0.jw5Mt5oGlnTi3j0r87AGA7zUK8dhMl_-53CGCK7WK1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);